### ISSUE TITLE
I'm unable to reproduce the examples from basic_tutorial.ipynb

### ISSUE THREAD

**Issue by colobas** [probcomp/trcrpm#1] opened 2018-08-15 17:11 UTC
Hey. I'm very interested in both your paper and implementation. However, when trying to reproduce the examples from `basic_tutorial.ipynb` these are the plots I got:
![trcrpm_example](https://user-images.githubusercontent.com/12519843/44161880-86271380-a0b6-11e8-919d-c98fbb13b28d.png)
![latent_example](https://user-images.githubusercontent.com/12519843/44161891-8b845e00-a0b6-11e8-876f-06f6c978cee4.png)
Any idea why this might be?

**Comment by fsaad** [comment] 2018-08-15 17:20
Hi @colobas, thanks for the question.

The tutorial notebook specifies around 20 seconds of MCMC inference in the line `model.resample_all(seconds=20)`, which in the notebook rendered posted to Github reports:
```
In [11]: model.resample_all(seconds=20)
Completed: 114 iterations in 20.013755 seconds.
Completed: 112 iterations in 20.018023 seconds.
Completed: 71 iterations in 20.011768 seconds.
Completed: 123 iterations in 20.047407 seconds.
```

Could you let me know how many iterations were printed in your notebook when you ran it on your machine?

You can also trying using `model.resample_all(steps=150)` to make sure you run at least as much as many steps of inference as were run in the online notebook.

**Comment by colobas** [comment] 2018-08-15 18:13
Hey, thx for the quick reply. Here is the output:
```
Completed: 38 iterations in 10.105366 seconds.
Completed: 27 iterations in 10.173081 seconds.
Completed: 33 iterations in 10.264232 seconds.
Completed: 18 iterations in 10.280439 seconds.
```
Clearly much less iterations, so that might be the cause. I'm trying it out by setting it by `steps`, as you suggested. But it seems to be spending (almost) no time in `resample_all` and most of the time in `resample_hyperparameters`. Specifically:

I run
```
(...)
print("resampling all")
t = time.time()
model.resample_all(steps=200)
f = time.time() - t
print(f)

print("resampling hyperparams")
t = time.time()
model.resample_hyperparameters(steps=150)
f = time.time() - t
print(f)
(...)
```

And this yields:
```
resampling all
6.59114599228
resampling hyperparams
Completed: 150 iterations in 36.450282 seconds.
Completed: 150 iterations in 51.329514 seconds.
Completed: 150 iterations in 63.971312 seconds.
Completed: 150 iterations in 75.198978 seconds.
75.2400448322
```

**Comment by fsaad** [comment] 2018-10-07 14:30
Hi @colobas, did increasing the iteration counts resolve this issue?

**Comment by colobas** [comment] 2018-10-07 15:45
Hey,
I haven't touched this for a while now, but from what I recall it didn't help much. I'll try it again sometime this week, and I'll let you know how it goes
Guilherme Grijó Pires

mail@gpir.es <mailto:mail@gpir.es>
+351 91 504 94 34


7. Out 2018 15:30 por notifications@github.com <mailto:notifications@github.com>:

**Comment by fsaad** [comment] 2018-12-05 21:35
@colobas Thanks for the report. I'll close this ticket since there doesn't seem to be a particular bug that's reproducible, but feel free to re-open it you're still experiencing issues.

**Closed as completed by fsaad** 2018-12-05 21:35 UTC
